# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.9

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/snowdrop/k8s-supervisor

    steps:
    # The checkout step will default to the working_directory we have already defined.
    - checkout

    - run:
        name: Perform build
        command: |
          make build

  release:
    docker:
    - image: circleci/golang:1.9

    working_directory: /go/src/github.com/k8s-supervisor/generator

    steps:
    - checkout

    - run:
        name: Install gox
        command: |
          go get github.com/mitchellh/gox

    - run:
        name: Install file
        command:
          sudo apt-get install file

    - run:
        name: Perform release
        command: |
          tagRE='release-(.*)'
          if [[ "${CIRCLE_TAG}" =~ ${tagRE} ]]; then
            # This will use gox to create the artifacts and the scripts in scripts to do the actual release
            # For the is to work, the GITHUB_API_TOKEN env var needs to be set in the CircleCI config
            make upload VERSION=${BASH_REMATCH[1]}
          else
            echo "${CIRCLE_TAG} does NOT match the expected pattern. This is probably a job configuration issue"
            exit 1
          fi

workflows:
  version: 2
  simple-build:
    jobs:
    - build
  release-build:
    jobs:
    - release:
        filters:
          tags:
            only: /^release-.*$/
          branches:
            ignore: /.*/
